spring.application.name=gamestore

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/game_store
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.show-sql=true

spring.datasource.username=COLOCAR_USUARIO
spring.datasource.password=COLOCAR_CONTRASEÑA
spring.datasource.driver-class-name=org.postgresql.Driver

